# Generated by Django 4.2.7 on 2023-12-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='function_name',
            field=models.CharField(max_length=40),
        ),
    ]
