# Generated by Django 4.2.7 on 2023-12-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='cases',
            field=models.JSONField(default=[[1], 1]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
