# Generated by Django 4.2.7 on 2023-12-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_challenge_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.TextField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', verbose_name='Difficulty'),
        ),
    ]
